### ISSUE TITLE
LED for MH-Tiny is PD0 and not PB0

### ISSUE THREAD

**Issue by mcuee** [stefanrueger/urboot.hex#1]
Somehow the LED is wrong for the MH-Tiny ATtiny88 board.

Pin-out reference
![89062312-803fa100-d366-11ea-9142-69c36b0ca764](https://user-images.githubusercontent.com/1294740/210173106-918c4904-c284-4c3d-9027-566bb9b18dc1.png)

**Comment by stefanrueger** [comment]
Thanks - corrected!
