### ISSUE TITLE
Missing pre-compiled binaries for ATmega324PB

### ISSUE THREAD

**Issue by MCUdude** [stefanrueger/urboot.hex#2]
There are no pre-compiled binaries for ATmega324PB in this repo.
It would be great if this could be added!

**Comment by stefanrueger** [comment]
@MCUdude Done; if you can please test one or two so this issue can be closed

**Comment by MCUdude** [comment]
Thanks! I've tested several auto-baud bootloaders, vbl, and hw bootloaders, and they all work great on the 324PB!
