### ISSUE TITLE
Failed to see difference between WDT_1s aand WDT_2s for manual RST (Pro Mini) on download

### ISSUE THREAD

**Issue by Erik84750** [stefanrueger/urboot.hex#5]
When programming a Pro Mini (Arduino IDE and Minicore v3.0) without DTR (ie with manual RST button-release right after bootloader initiates "ready for download": on Arduino IDE the green "compile finished" bar is fully to the right) I fail to see the difference in the time-window for releasing the RST button between WDT_1s and WDT_2s bootloaders.
I even suspect that WDT_1s does not give a full 1 second time-window between "start-of-download-signal" on Arduino IDE (when the green "compiling" bar is fully extended) and RST button-release on Pro Mini.

Or does the WDT apply to the timing right before "compile finished" indication on the Arduino IDE?

**Comment by stefanrueger** [comment]
The WDT is the time that the bootloader listens to the USART for uploading commands from the host PC right after *releasing* the reset button. If there were no uploading commands from the PC to the board during that time the bootloader jumps to the application, which then can use the USART for its own purposes.

The trouble with some IDEs is that pressing their upload button first initiates the compilation of the source, which takes an unknown duration: only once the .hex file has been compiled the host can send it to the board/bootloader via uploading commands to the USART. This means that the user has to release the reset button *just before* compilation ends upon which proper uploading starts. This involves guesswork and experience. If the bootloader has a WDT of 2 seconds the user can release the reset button up to 2 seconds before compilation ends. Release the reset button earlier than that and the board will already process the application when the host tries to upload (and the uploading commands fail). Release the reset button after the host has started sending uploading commands and the bootloader is at danger of not being able to synchronise with the host (and the uploading commands might fail).

You can measure the WDT by uploading an application that, say, switches on a light. Press reset and measure the time after releasing the reset button until the light is switched on.

There is a trade-off between a short WDT (application starts soon after releasing reset) and a long WDT (after releasing reset, the user can  afford to make a cup of coffee before pressing the upload button in their IDE).

**Comment by Erik84750** [comment]
Many thanks Stefan for your complete and very courteous answer!.
"If the bootloader has a WDT of 2 seconds the user can release the reset button up to 2 seconds before compilation ends." ..that solves my problem. Thank you Stefan, much appreciated!.
